import { ITournamentMatch } from './i-tournament-bracket-item';

export const TOURNAMENT_SEED_DATA: ITournamentMatch[] = [
  {
    id: 'ub-qf-1',
    phase: 'UB Quarterfinal',
    bracket: 'upper',
    roundIndex: 0,
    date: new Date(2026, 3, 10, 14, 0),
    status: 'completed',
    competitors: [
      { name: 'Xtreme Gaming', score: 0 },
      { name: 'Team Liquid', score: 2, isWinner: true },
    ],
    nextMatchId: 'ub-sf-1',
  },
  {
    id: 'ub-qf-2',
    phase: 'UB Quarterfinal',
    bracket: 'upper',
    roundIndex: 0,
    date: new Date(2026, 3, 10, 17, 0),
    status: 'completed',
    competitors: [
      { name: 'Cloud9', score: 2, isWinner: true },
      { name: 'Aurora Gaming', score: 0 },
    ],
    nextMatchId: 'ub-sf-1',
  },
  {
    id: 'ub-qf-3',
    phase: 'UB Quarterfinal',
    bracket: 'upper',
    roundIndex: 0,
    date: new Date(2026, 3, 10, 20, 0),
    status: 'completed',
    competitors: [
      { name: 'Team Falcons', score: 0 },
      { name: 'Tundra Esport', score: 2, isWinner: true },
    ],
    nextMatchId: 'ub-sf-2',
  },
  {
    id: 'ub-qf-4',
    phase: 'UB Quarterfinal',
    bracket: 'upper',
    roundIndex: 0,
    date: new Date(2026, 3, 11, 14, 0),
    status: 'completed',
    competitors: [
      { name: 'Nouns', score: 1 },
      { name: 'Gaimin Gladiators', score: 2, isWinner: true },
    ],
    nextMatchId: 'ub-sf-2',
  },
  {
    id: 'ub-sf-1',
    phase: 'UB Semifinal',
    bracket: 'upper',
    roundIndex: 1,
    date: new Date(2026, 3, 12, 15, 0),
    status: 'completed',
    competitors: [
      { name: 'Team Liquid', score: 2, isWinner: true },
      { name: 'Cloud9', score: 0 },
    ],
    nextMatchId: 'ub-final',
  },
  {
    id: 'ub-sf-2',
    phase: 'UB Semifinal',
    bracket: 'upper',
    roundIndex: 1,
    date: new Date(2026, 3, 12, 18, 0),
    status: 'completed',
    competitors: [
      { name: 'Tundra Esport', score: 0 },
      { name: 'Gaimin Gladiators', score: 2, isWinner: true },
    ],
    nextMatchId: 'ub-final',
  },
  {
    id: 'ub-final',
    phase: 'UB Final',
    bracket: 'upper',
    roundIndex: 2,
    date: new Date(2026, 3, 13, 18, 0),
    status: 'completed',
    competitors: [
      { name: 'Team Liquid', score: 2, isWinner: true },
      { name: 'Gaimin Gladiators', score: 0 },
    ],
    nextMatchId: 'grand-final',
  },
  {
    id: 'lb-r1-1',
    phase: 'LB Round 1',
    bracket: 'lower',
    roundIndex: 0,
    date: new Date(2026, 3, 11, 14, 0),
    status: 'completed',
    competitors: [
      { name: 'Talon', score: 1 },
      { name: 'BetBoom Team', score: 2, isWinner: true },
    ],
    nextMatchId: 'lb-r2-1',
  },
  {
    id: 'lb-r1-2',
    phase: 'LB Round 1',
    bracket: 'lower',
    roundIndex: 0,
    date: new Date(2026, 3, 11, 17, 0),
    status: 'completed',
    competitors: [
      { name: '1w Team', score: 2, isWinner: true },
      { name: 'Team Zero', score: 0 },
    ],
    nextMatchId: 'lb-r2-2',
  },
  {
    id: 'lb-r1-3',
    phase: 'LB Round 1',
    bracket: 'lower',
    roundIndex: 0,
    date: new Date(2026, 3, 11, 20, 0),
    status: 'completed',
    competitors: [
      { name: 'Beastcoast', score: 1 },
      { name: 'Heroic', score: 2, isWinner: true },
    ],
    nextMatchId: 'lb-r2-3',
  },
  {
    id: 'lb-r1-4',
    phase: 'LB Round 1',
    bracket: 'lower',
    roundIndex: 0,
    date: new Date(2026, 3, 12, 12, 0),
    status: 'completed',
    competitors: [
      { name: 'Team Spirit', score: 2, isWinner: true },
      { name: 'Invictus Gaming', score: 0 },
    ],
    nextMatchId: 'lb-r2-4',
  },
  {
    id: 'lb-r2-1',
    phase: 'LB Round 2',
    bracket: 'lower',
    roundIndex: 1,
    date: new Date(2026, 3, 13, 12, 0),
    status: 'completed',
    competitors: [
      { name: 'Nouns', score: 0 },
      { name: 'BetBoom Team', score: 2, isWinner: true },
    ],
    nextMatchId: 'lb-r3-1',
  },
  {
    id: 'lb-r2-2',
    phase: 'LB Round 2',
    bracket: 'lower',
    roundIndex: 1,
    date: new Date(2026, 3, 13, 15, 0),
    status: 'completed',
    competitors: [
      { name: 'Team Falcons', score: 2, isWinner: true },
      { name: '1w Team', score: 0 },
    ],
    nextMatchId: 'lb-r3-1',
  },
  {
    id: 'lb-r2-3',
    phase: 'LB Round 2',
    bracket: 'lower',
    roundIndex: 1,
    date: new Date(2026, 3, 13, 18, 0),
    status: 'completed',
    competitors: [
      { name: 'Aurora Gaming', score: 2, isWinner: true },
      { name: 'Heroic', score: 1 },
    ],
    nextMatchId: 'lb-r3-2',
  },
  {
    id: 'lb-r2-4',
    phase: 'LB Round 2',
    bracket: 'lower',
    roundIndex: 1,
    date: new Date(2026, 3, 14, 12, 0),
    status: 'completed',
    competitors: [
      { name: 'Xtreme Gaming', score: 2, isWinner: true },
      { name: 'Team Spirit', score: 1 },
    ],
    nextMatchId: 'lb-r3-2',
  },
  {
    id: 'lb-r3-1',
    phase: 'LB Round 3',
    bracket: 'lower',
    roundIndex: 2,
    date: new Date(2026, 3, 14, 15, 0),
    status: 'completed',
    competitors: [
      { name: 'BetBoom Team', score: 0 },
      { name: 'Team Falcons', score: 2, isWinner: true },
    ],
    nextMatchId: 'lb-r4-1',
  },
  {
    id: 'lb-r3-2',
    phase: 'LB Round 3',
    bracket: 'lower',
    roundIndex: 2,
    date: new Date(2026, 3, 14, 18, 0),
    status: 'completed',
    competitors: [
      { name: 'Aurora Gaming', score: 0 },
      { name: 'Xtreme Gaming', score: 2, isWinner: true },
    ],
    nextMatchId: 'lb-r4-2',
  },
  {
    id: 'lb-r4-1',
    phase: 'LB Round 4',
    bracket: 'lower',
    roundIndex: 3,
    date: new Date(2026, 3, 15, 15, 0),
    status: 'completed',
    competitors: [
      { name: 'Cloud9', score: 0 },
      { name: 'Team Falcons', score: 2, isWinner: true },
    ],
    nextMatchId: 'lb-r5',
  },
  {
    id: 'lb-r4-2',
    phase: 'LB Round 4',
    bracket: 'lower',
    roundIndex: 3,
    date: new Date(2026, 3, 15, 18, 0),
    status: 'completed',
    competitors: [
      { name: 'Tundra Esport', score: 2, isWinner: true },
      { name: 'Xtreme Gaming', score: 0 },
    ],
    nextMatchId: 'lb-r5',
  },
  {
    id: 'lb-r5',
    phase: 'LB Round 5',
    bracket: 'lower',
    roundIndex: 4,
    date: new Date(2026, 3, 16, 15, 0),
    status: 'completed',
    competitors: [
      { name: 'Team Falcons', score: 0 },
      { name: 'Tundra Esport', score: 2, isWinner: true },
    ],
    nextMatchId: 'lb-final',
  },
  {
    id: 'lb-final',
    phase: 'LB Final',
    bracket: 'lower',
    roundIndex: 5,
    date: new Date(2026, 3, 16, 18, 0),
    status: 'completed',
    competitors: [
      { name: 'Gaimin Gladiators', score: 2, isWinner: true },
      { name: 'Tundra Esport', score: 1 },
    ],
    nextMatchId: 'grand-final',
  },
  {
    id: 'grand-final',
    phase: 'Grand Final',
    bracket: 'final',
    roundIndex: 0,
    date: new Date(2026, 3, 17, 18, 0),
    status: 'completed',
    competitors: [
      { name: 'Team Liquid', score: 3, isWinner: true },
      { name: 'Gaimin Gladiators', score: 0 },
    ],
  },
];
