name: Feature request
description: Suggest an idea for Foblex Flow
labels:
  - enhancement
assignees:
  - siarheihuzarevich
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the feature you want to propose.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
