export const PINCH_NORMALIZATION_FACTOR = 100;
export const PINCH_NORMALIZATION_RATIO = 1 / PINCH_NORMALIZATION_FACTOR;
export const PINCH_MOVEMENT_THRESHOLD = 0.5;
export const NORMALIZED_MIN = 0.1;
export const NORMALIZED_MAX = 1;
