import { inject, Injectable } from '@angular/core';
import { IPoint, IRect, RectExtensions } from '@foblex/2d';
import { FMediator } from '@foblex/mediator';
import { FComponentsStore, INSTANCES } from '../../f-storage';
import { FNodeBase } from '../../f-node';
import { FConnectionBase } from '../../f-connection-v2';
import { FConnectorDirective, FSourceConnectorBase } from '../../f-connectors';
import {
  EmitSelectionChangeEventRequest,
  FCreateConnectionSession,
  FDeleteSelectedEvent,
  FDraggableDataContext,
  FMoveNodesEvent,
  isDragBlocker,
} from '../../f-draggable';
import {
  ClearSelectionRequest,
  GetCurrentSelectionRequest,
  ICurrentSelection,
  IConnectorRectRef,
  SelectAllRequest,
  SelectRequest,
} from '../../domain';
import { FA11yAnnouncer } from './f-a11y-announcer';
import { F_A11Y_CONFIG, F_DEFAULT_A11Y_CONFIG, IFA11yResolvedConfig } from './i-f-a11y';
import { FA11yDirection, findSpatialNeighbor, IFA11yNavigable } from './f-a11y-navigation';

let instructionsUniqueId = 0;
let itemUniqueId = 0;

const ARROW_DIRECTIONS: Record<string, FA11yDirection> = {
  // eslint-disable-next-line @typescript-eslint/naming-convention
  ArrowUp: 'up',
  // eslint-disable-next-line @typescript-eslint/naming-convention
  ArrowDown: 'down',
  // eslint-disable-next-line @typescript-eslint/naming-convention
  ArrowLeft: 'left',
  // eslint-disable-next-line @typescript-eslint/naming-convention
  ArrowRight: 'right',
};

/** Native interactive content the keyboard layer must never hijack (inputs, buttons, links…). */
const INTERACTIVE_CONTENT_SELECTOR =
  'input, textarea, select, button, a[href], audio[controls], video[controls], summary, ' +
  '[contenteditable]:not([contenteditable="false"]), [tabindex]:not([tabindex="-1"])';

/** Marks labels generated by this layer, so they refresh without touching consumer-set ones. */
const GENERATED_LABEL_ATTRIBUTE = 'data-f-a11y-generated-label';

/** The keyboard-zoom surface of `FZoomDirective`, duck-typed to avoid a hard reference. */
interface IZoomLike {
  zoomIn(): void;
  zoomOut(): void;
  reset(): void;
  getZoomValue(): number;
}

/** The viewport surface of `FCanvasComponent`, duck-typed from `FCanvasBase`. */
interface ICenterLike {
  centerGroupOrNode(id: string, animated?: boolean): void;
}

interface IMoveItem {
  node: FNodeBase;
  origin: IPoint;
  // Tracked here because `position.set()` syncs `_position` in an effect (next CD
  // tick) — reading `_position` per keystroke would lose intermediate steps.
  current: IPoint;
}

/** Keyboard movement grabs the WHOLE selection, matching what a pointer drag moves. */
interface IMoveState {
  items: IMoveItem[];
  label: string;
  /** The grabbing `Space` is still physically held (quasimode candidate). */
  spaceHeld: boolean;
  /** An arrow moved the items while `Space` was held — releasing it then drops. */
  movedWhileHeld: boolean;
}

interface IConnectState {
  source: FSourceConnectorBase;
  sourceLabel: string;
  targets: IConnectorRectRef[];
  index: number;
  lastMove?: { fromId: string; toId: string; direction: FA11yDirection };
}

/**
 * The accessibility engine of a flow, always provided at the `f-flow` injector.
 * `FFlowComponent` calls {@link initialize} and {@link destroy}; consumers configure it
 * through `withA11y(...)` and never drive it directly.
 *
 * The SEMANTIC layer runs unconditionally: the host becomes the widget's entry point
 * (`role="application"`, so screen readers hand the arrow keys to the canvas, with the
 * keyboard instructions as its description), nodes, groups and connections get roles
 * and accessible names as they register, and every state change is spoken through
 * {@link FA11yAnnouncer} with strings from the localizable catalog.
 *
 * The KEYBOARD layer (on by default, `withA11y({ keyboard: false })` turns it off)
 * drives roving focus from the host — the single tab stop — with SELECTION FOLLOWING
 * FOCUS, the same model a pointer click produces:
 * - arrows — spatial navigation (TV-style rect-based algorithm) that focuses AND
 *   selects the nearest node; `Shift`+arrow extends the selection; `Home`/`End` —
 *   first/last node;
 * - `Ctrl`+arrow — topology walk: the connection in that direction (focused and
 *   selected, so `Delete` works on it), then the node on its other end;
 * - `Ctrl`+`A` selects all, `Escape` clears;
 * - `Space` grabs the focused node: arrows move it (`Shift` for coarse steps), `Space`
 *   drops (emits `fMoveNodes`), `Escape` reverts;
 * - `C` starts a connection from the focused node through the shared
 *   {@link FCreateConnectionSession}: arrows cycle connectable targets with the same
 *   preview and snap as pointer gestures, `Enter` emits `fCreateConnection`, `Escape`
 *   cancels;
 * - `Delete`/`Backspace` emits `fDeleteSelected` — the library never mutates the graph;
 * - `+`/`-`/`0` zoom via the registered zoom plugin.
 */
@Injectable()
export class FA11yController {
  private readonly _store = inject(FComponentsStore);
  private readonly _mediator = inject(FMediator);
  private readonly _dragContext = inject(FDraggableDataContext);
  private readonly _session = inject(FCreateConnectionSession);
  private readonly _announcer = inject(FA11yAnnouncer);
  private readonly _config: IFA11yResolvedConfig =
    inject(F_A11Y_CONFIG, { optional: true }) ?? F_DEFAULT_A11Y_CONFIG;

  private _disposers: (() => void)[] = [];
  private _instructionsId: string | undefined;

  private _activeNodeId: string | undefined;
  private _activeConnectionId: string | undefined;
  private _walkTargetNodeId: string | undefined;
  private _lastMove: { fromId: string; toId: string; direction: FA11yDirection } | undefined;

  private _move: IMoveState | null = null;
  private _connect: IConnectState | null = null;

  private get _messages() {
    return this._config.messages;
  }

  private get _host(): HTMLElement {
    return this._store.flowHost;
  }

  /** Called once by `FFlowComponent` after content init (browser only). */
  public initialize(): void {
    this._disposers.push(
      this._store.nodesChanges$.listen(() => {
        this._applySemantics();
        this._invalidateModes();
      }),
      this._store.connectionsChanges$.listen(() => {
        this._applySemantics();
        this._invalidateModes();
      }),
    );
    this._applySemantics();

    if (!this._config.keyboard) {
      return;
    }

    if (!this._host.hasAttribute('tabindex')) {
      this._host.setAttribute('tabindex', '0');
    }

    const keydown = (event: KeyboardEvent) => this._onKeyDown(event);
    const keyup = (event: KeyboardEvent) => this._onKeyUp(event);
    const pointerdown = (event: PointerEvent) => this._onPointerDown(event);
    this._host.addEventListener('keydown', keydown);
    this._host.addEventListener('keyup', keyup);
    this._host.addEventListener('pointerdown', pointerdown);
    this._disposers.push(
      () => this._host.removeEventListener('keydown', keydown),
      () => this._host.removeEventListener('keyup', keyup),
      () => this._host.removeEventListener('pointerdown', pointerdown),
    );
  }

  /** Called by `FFlowComponent` on destroy; cancels active modes and removes listeners. */
  public destroy(): void {
    this._cancelModes();
    for (const dispose of this._disposers) {
      dispose();
    }
    this._disposers = [];
  }

  // ------------------------------------------------------------------ semantics

  private _applySemantics(): void {
    // With the keyboard layer on, the host is the widget's entry point:
    // `application` hands the arrow keys to the canvas in screen-reader focus mode
    // (browse mode would swallow them) and makes a consumer-set `aria-label` valid.
    // WITHOUT the keyboard layer the role would be harmful — focus mode disables the
    // virtual cursor while nobody handles the keys — so a semantics-only flow stays
    // a plain readable region and gets no instructions for keys that do not exist.
    if (this._config.keyboard) {
      this._setIfAbsent(this._host, 'role', 'application');
      this._setIfAbsent(this._host, 'aria-roledescription', this._messages.flow);
      this._setIfAbsent(this._host, 'aria-describedby', this._ensureInstructionsElement());
    }

    for (const node of this._store.nodes.getAll()) {
      const element = node.hostElement;
      this._ensureItemId(element);
      this._setIfAbsent(element, 'role', 'group');
      this._setIfAbsent(
        element,
        'aria-roledescription',
        element.hasAttribute('data-f-group-id') ? this._messages.group : this._messages.node,
      );
    }

    for (const connection of this._store.connections.getAll()) {
      const element = connection.hostElement as HTMLElement;
      this._ensureItemId(element);
      this._setIfAbsent(element, 'role', 'group');
      this._setIfAbsent(element, 'aria-roledescription', this._messages.connection);
      this._refreshGeneratedLabel(element, connection);
    }
  }

  /**
   * The generated connection name tracks its endpoints; a label the consumer set
   * themselves (`aria-label` without the marker attribute) is never touched.
   */
  private _refreshGeneratedLabel(element: HTMLElement, connection: FConnectionBase): void {
    const generated = this._messages.connectionLabel(connection.sourceId(), connection.targetId());
    if (!element.hasAttribute('aria-label')) {
      element.setAttribute('aria-label', generated);
      element.setAttribute(GENERATED_LABEL_ATTRIBUTE, '');

      return;
    }
    if (element.hasAttribute(GENERATED_LABEL_ATTRIBUTE)) {
      element.setAttribute('aria-label', generated);
    }
  }

  private _ensureInstructionsElement(): string {
    if (this._instructionsId) {
      return this._instructionsId;
    }
    const id = `f-a11y-instructions-${instructionsUniqueId++}`;
    const element = this._host.ownerDocument.createElement('div');
    element.id = id;
    element.textContent = this._messages.instructions;
    element.style.display = 'none';
    this._host.appendChild(element);
    this._instructionsId = id;

    return id;
  }

  private _setIfAbsent(element: Element, attribute: string, value: string): void {
    if (!element.hasAttribute(attribute)) {
      element.setAttribute(attribute, value);
    }
  }

  /** `aria-activedescendant` needs a DOM id; generated only when the consumer set none. */
  private _ensureItemId(element: Element): string {
    if (!element.id) {
      element.id = `f-a11y-item-${itemUniqueId++}`;
    }

    return element.id;
  }

  /** DOM focus never leaves the host — the active item is conveyed to AT here. */
  private _setActiveDescendant(element: Element | undefined): void {
    if (element) {
      this._host.setAttribute('aria-activedescendant', this._ensureItemId(element));
    } else {
      this._host.removeAttribute('aria-activedescendant');
    }
  }

  /** Active modes must not outlive the items they hold — data can change under them. */
  private _invalidateModes(): void {
    const move = this._move;
    if (move) {
      const alive = this._store.nodes.getAll();
      move.items = move.items.filter((x) => alive.includes(x.node));
      if (!move.items.length) {
        this._move = null;
        this._announce(this._messages.moveCancelled(move.label), 'assertive');
      }
    }

    const connect = this._connect;
    if (connect) {
      const connectors = new Set(
        this._store.nodes.getAll().flatMap((x) => x.connectors.map((c) => c.fId())),
      );
      const gone =
        !connectors.has(connect.source.fId()) ||
        connect.targets.some((x) => !connectors.has(x.connector.fId()));
      if (gone) {
        this._session.cancel();
        this._connect = null;
        this._announce(this._messages.connectCancelled, 'assertive');
      }
    }
  }

  // ------------------------------------------------------------------ keyboard

  /**
   * A pointer interaction keeps the keyboard layer live: the host takes DOM focus (a
   * plain div would otherwise drop it to `<body>`), and the clicked item becomes the
   * active one, so the next arrow continues from where the user pointed.
   */
  private _onPointerDown(event: PointerEvent): void {
    const target = event.target as HTMLElement;
    if (this._isInteractiveContent(target)) {
      return;
    }

    this._host.focus({ preventScroll: true });

    const node = this._store.nodes.getAll().find((x) => x.isContains(target));
    if (node) {
      this._activeNodeId = node.fId();
      this._activeConnectionId = undefined;
      this._setActiveDescendant(node.hostElement);

      return;
    }

    const connection = this._store.connections
      .getAll()
      .find((x) => x.hostElement === target || x.hostElement.contains(target));
    if (connection) {
      this._activeConnectionId = connection.fId();
      this._activeNodeId = undefined;
      this._setActiveDescendant(connection.hostElement as HTMLElement);
    }
  }

  private _onKeyDown(event: KeyboardEvent): void {
    const target = event.target as HTMLElement;
    if (this._isInteractiveContent(target)) {
      return;
    }

    const connect = this._connect;
    if (connect) {
      this._handleConnectMode(event, connect);

      return;
    }
    const move = this._move;
    if (move) {
      this._handleMoveMode(event, move);

      return;
    }

    const direction = ARROW_DIRECTIONS[event.key];
    if (direction) {
      event.preventDefault();
      event.ctrlKey || event.metaKey
        ? this._walkConnections(direction, event.shiftKey)
        : this._navigate(direction, event.shiftKey);

      return;
    }

    if (event.key === 'Home') {
      event.preventDefault();
      this._focusNodeAt(0);

      return;
    }
    if (event.key === 'End') {
      event.preventDefault();
      this._focusNodeAt(this._navigableNodes().length - 1);

      return;
    }
    if (event.key === 'Escape') {
      this._clearSelection();

      return;
    }

    const keys = this._config.keys;
    // Single-character bindings yield to OS shortcuts (Ctrl/Cmd+C stays copy).
    const hasModifier = event.ctrlKey || event.metaKey || event.altKey;

    if (this._matchesKey(event, keys.grab)) {
      event.preventDefault();
      if (!event.repeat) {
        this._beginMove();
      }

      return;
    }
    if (this._matchesKey(event, keys.deleteSelected)) {
      event.preventDefault();
      this._requestDelete();

      return;
    }
    if (this._matchesKey(event, keys.selectAll) && (event.ctrlKey || event.metaKey)) {
      event.preventDefault();
      this._selectAll();

      return;
    }
    if (hasModifier) {
      return;
    }
    if (this._matchesKey(event, keys.connect)) {
      this._beginConnect(event);
    } else if (this._matchesKey(event, keys.zoomIn)) {
      this._zoom((zoom) => zoom.zoomIn());
    } else if (this._matchesKey(event, keys.zoomOut)) {
      this._zoom((zoom) => zoom.zoomOut());
    } else if (this._matchesKey(event, keys.zoomReset)) {
      this._zoom((zoom) => zoom.reset());
    }
  }

  /** Single-character bindings match case-insensitively; named keys match exactly. */
  private _matchesKey(event: KeyboardEvent, keys: string[]): boolean {
    return keys.some((key) =>
      key.length === 1 ? key.toLowerCase() === event.key.toLowerCase() : key === event.key,
    );
  }

  /** Keys must never hijack typing or native controls inside a node. */
  private _isInteractiveContent(target: HTMLElement): boolean {
    if (target === this._host) {
      return false;
    }
    if (this._store.nodes.getAll().some((x) => x.hostElement === target)) {
      return false;
    }
    if (this._store.connections.getAll().some((x) => x.hostElement === target)) {
      return false;
    }

    return (
      !!target.closest(INTERACTIVE_CONTENT_SELECTOR) ||
      isDragBlocker(target) ||
      !!target.closest('[fLockedContext]')
    );
  }

  // ------------------------------------------------------------------ navigation

  /**
   * Plain arrows travel over nodes AND connections as equal stops — a connection is
   * represented by its midpoint, so walking a chain reads node → connection → node.
   */
  private _navigate(direction: FA11yDirection, extendSelection: boolean): void {
    const origin = this._currentOriginRect();
    if (!origin) {
      this._focusNodeAt(0);

      return;
    }

    const currentNode = this._activeNode();
    const currentKey = currentNode
      ? `n:${currentNode.fId()}`
      : this._activeConnectionId
        ? `c:${this._activeConnectionId}`
        : undefined;

    const pool: IFA11yNavigable[] = this._navigableNodes()
      .filter((x) => x !== currentNode)
      .map((x) => ({ id: `n:${x.fId()}`, rect: this._nodeRect(x) }));
    for (const connection of this._store.connections.getAll()) {
      if (connection.fId() === this._activeConnectionId) {
        continue;
      }
      const midpoint = this._connectionMidpoint(connection);
      if (midpoint) {
        pool.push({
          id: `c:${connection.fId()}`,
          rect: RectExtensions.initialize(midpoint.x, midpoint.y, 0, 0),
        });
      }
    }
    if (!pool.length) {
      return;
    }

    const preferredId =
      this._lastMove &&
      this._lastMove.toId === currentKey &&
      this._lastMove.direction === oppositeOf(direction)
        ? this._lastMove.fromId
        : undefined;

    const next = findSpatialNeighbor(origin, pool, direction, preferredId);
    if (!next) {
      return;
    }

    if (currentKey) {
      this._lastMove = { fromId: currentKey, toId: next.id, direction };
    }

    if (next.id.startsWith('n:')) {
      this._focusNode(next.id.slice(2), extendSelection);
    } else {
      const connection = this._store.connections.getAll().find((x) => x.fId() === next.id.slice(2));
      if (connection) {
        this._focusConnection(connection, undefined, extendSelection);
      }
    }
  }

  /** Origin for spatial navigation: the focused node's rect or the focused connection's midpoint. */
  private _currentOriginRect(): IRect | undefined {
    const node = this._activeNode();
    if (node) {
      return this._nodeRect(node);
    }

    const midpoint = this._connectionMidpoint(this._activeConnection());

    return midpoint ? RectExtensions.initialize(midpoint.x, midpoint.y, 0, 0) : undefined;
  }

  private _walkConnections(direction: FA11yDirection, extendSelection: boolean): void {
    // On a connection the walk continues to the node it points at (or the endpoint
    // lying in the pressed direction when the connection was reached by plain arrows).
    const focusedConnection = this._activeConnection();
    if (focusedConnection) {
      const targetId =
        this._walkTargetNodeId ?? this._endpointInDirection(focusedConnection, direction);
      if (targetId) {
        this._focusNode(targetId, extendSelection);
      }

      return;
    }

    const node = this._activeNode();
    if (!node) {
      this._focusNodeAt(0);

      return;
    }

    const owners = this._connectorOwners();
    const candidates: IFA11yNavigable[] = [];
    const byOther = new Map<string, { connection: FConnectionBase; other: FNodeBase }>();

    for (const connection of this._store.connections.getAll()) {
      const source = owners.get(connection.sourceId());
      const target = owners.get(connection.targetId());
      const other: FNodeBase | undefined =
        source === node ? target : target === node ? source : undefined;
      if (!other || other === node) {
        continue;
      }
      candidates.push({ id: other.fId(), rect: this._nodeRect(other) });
      byOther.set(other.fId(), { connection, other });
    }

    const nearest = findSpatialNeighbor(this._nodeRect(node), candidates, direction);
    const walk = nearest ? byOther.get(nearest.id) : undefined;
    if (!walk) {
      return;
    }

    this._focusConnection(walk.connection, walk.other.fId(), extendSelection);
  }

  /** Makes a connection the active item and selects it; DOM focus stays on the host. */
  private _focusConnection(
    connection: FConnectionBase,
    walkTargetNodeId: string | undefined,
    extendSelection: boolean,
  ): void {
    const element = connection.hostElement as HTMLElement;
    this._activeConnectionId = connection.fId();
    this._activeNodeId = undefined;
    this._walkTargetNodeId = walkTargetNodeId;
    this._setActiveDescendant(element);

    if (extendSelection) {
      const current = this._selection();
      this._applySelection(
        [...current.fNodeIds, ...current.fGroupIds],
        [...current.fConnectionIds, connection.fId()],
      );
    } else {
      this._applySelection([], [connection.fId()]);
    }
    this._announce(
      this._messages.connectionFocused(
        element.getAttribute('aria-label') ??
          this._messages.connectionLabel(connection.sourceId(), connection.targetId()),
      ),
    );
  }

  /** The endpoint node of a connection lying in the pressed direction (target-side default). */
  private _endpointInDirection(
    connection: FConnectionBase,
    direction: FA11yDirection,
  ): string | undefined {
    const owners = this._connectorOwners();
    const source = owners.get(connection.sourceId());
    const target = owners.get(connection.targetId());
    if (!source || !target) {
      return (target ?? source)?.fId();
    }

    const a = this._nodeCenter(source);
    const b = this._nodeCenter(target);
    const towardTarget =
      direction === 'right'
        ? b.x >= a.x
        : direction === 'left'
          ? b.x <= a.x
          : direction === 'down'
            ? b.y >= a.y
            : b.y <= a.y;

    return towardTarget ? target.fId() : source.fId();
  }

  private _focusNodeAt(index: number): void {
    const nodes = this._navigableNodes();
    const node = nodes[Math.max(0, Math.min(index, nodes.length - 1))];
    if (node) {
      this._focusNode(node.fId(), false);
    }
  }

  private _focusNode(id: string, extendSelection: boolean): void {
    const nodes = this._navigableNodes();
    const node = this._store.nodes.getAll().find((x) => x.fId() === id);
    if (!node) {
      return;
    }

    this._activeNodeId = id;
    this._activeConnectionId = undefined;
    this._walkTargetNodeId = undefined;
    this._setActiveDescendant(node.hostElement);

    // Arrows move the SELECTION directly — DOM focus stays on the host, the active
    // item is conveyed via aria-activedescendant, and the selected style is the one
    // and only visual state.
    if (extendSelection) {
      const current = this._selection();
      this._applySelection([...current.fNodeIds, ...current.fGroupIds, id], current.fConnectionIds);
    } else {
      this._applySelection([id], []);
    }

    this._bringIntoView(node);
    const index = nodes.indexOf(node);
    this._announce(
      this._messages.nodeFocused(
        this._nodeLabel(node),
        (index === -1 ? nodes.length : index) + 1,
        nodes.length,
      ),
    );
  }

  /** WCAG 2.4.11 — the focused node must not stay outside the visible viewport. */
  private _bringIntoView(node: FNodeBase): void {
    const rect = node.hostElement.getBoundingClientRect();
    const host = this._host.getBoundingClientRect();
    const outside =
      rect.right < host.left ||
      rect.left > host.right ||
      rect.bottom < host.top ||
      rect.top > host.bottom;

    const canvas = this._store.fCanvas as unknown as Partial<ICenterLike> | undefined;
    if (outside && canvas?.centerGroupOrNode) {
      canvas.centerGroupOrNode(node.fId(), false);
    }
  }

  // ------------------------------------------------------------------ selection

  private _applySelection(nodeAndGroupIds: string[], connectionIds: string[]): void {
    this._mediator.execute<void>(new SelectRequest(nodeAndGroupIds, connectionIds, true));
    this._mediator.execute<void>(new EmitSelectionChangeEventRequest());
  }

  private _selectAll(): void {
    this._mediator.execute<void>(new SelectAllRequest());
    this._dragContext.markSelectionAsChanged();
    this._mediator.execute<void>(new EmitSelectionChangeEventRequest());
    const selection = this._selection();
    this._announce(
      this._messages.allSelected(
        selection.fNodeIds.length + selection.fGroupIds.length + selection.fConnectionIds.length,
      ),
    );
  }

  private _clearSelection(): void {
    const selection = this._selection();
    const isEmpty =
      !selection.fNodeIds.length && !selection.fGroupIds.length && !selection.fConnectionIds.length;
    if (isEmpty) {
      return;
    }
    this._mediator.execute<void>(new ClearSelectionRequest());
    this._dragContext.markSelectionAsChanged();
    this._mediator.execute<void>(new EmitSelectionChangeEventRequest());
    this._announce(this._messages.selectionCleared);
  }

  private _requestDelete(): void {
    if (!this._store.fDraggable) {
      return;
    }
    const selection = this._selection();
    const count =
      selection.fNodeIds.length + selection.fGroupIds.length + selection.fConnectionIds.length;
    if (!count) {
      return;
    }

    this._store.fDraggable.fDeleteSelected.emit(
      new FDeleteSelectedEvent(selection.fNodeIds, selection.fGroupIds, selection.fConnectionIds),
    );
    this._announce(this._messages.deleteRequested(count), 'assertive');
  }

  // ------------------------------------------------------------------ move mode

  private _beginMove(): void {
    if (!this._store.fDraggable) {
      return;
    }

    // Grab everything the selection holds — a pointer drag moves the whole selection,
    // and the keyboard must not silently move less. Focused-but-unselectable nodes
    // still move alone as a fallback.
    const selection = this._selection();
    const selectedIds = new Set([...selection.fNodeIds, ...selection.fGroupIds]);
    let nodes = this._store.nodes
      .getAll()
      .filter((x) => selectedIds.has(x.fId()) && !x.fDraggingDisabled());

    const focused = this._activeNode();
    if (!nodes.length && focused && !focused.fDraggingDisabled()) {
      nodes = [focused];
    }
    if (!nodes.length) {
      return;
    }

    this._move = {
      items: nodes.map((node) => ({
        node,
        origin: { ...node._position },
        current: { ...node._position },
      })),
      label:
        nodes.length === 1 ? this._nodeLabel(nodes[0]) : this._messages.itemsCount(nodes.length),
      spaceHeld: true,
      movedWhileHeld: false,
    };
    this._announce(this._messages.grabbed(this._move.label));
  }

  private _handleMoveMode(event: KeyboardEvent, move: IMoveState): void {
    const direction = ARROW_DIRECTIONS[event.key];
    const anchor = move.items[0];

    if (direction) {
      event.preventDefault();
      const step = event.shiftKey ? this._config.coarseMoveStep : this._config.moveStep;
      const delta = {
        up: { x: 0, y: -step },
        down: { x: 0, y: step },
        left: { x: -step, y: 0 },
        right: { x: step, y: 0 },
      }[direction];

      for (const item of move.items) {
        item.current = { x: item.current.x + delta.x, y: item.current.y + delta.y };
        item.node.position.set({ ...item.current });
      }
      if (move.spaceHeld) {
        move.movedWhileHeld = true;
      }
      this._announce(
        this._messages.moved(Math.round(anchor.current.x), Math.round(anchor.current.y)),
      );

      return;
    }

    if (this._matchesKey(event, this._config.keys.grab) || event.key === 'Enter') {
      event.preventDefault();
      // A held grab key autorepeats — only a genuine second press (or Enter) drops
      // here; the hold-to-move path drops on the grab key's keyup instead.
      if (event.repeat || (event.key !== 'Enter' && move.spaceHeld)) {
        return;
      }
      this._dropMove(move);

      return;
    }

    if (event.key === 'Escape') {
      event.preventDefault();
      for (const item of move.items) {
        item.node.position.set({ ...item.origin });
      }
      this._announce(this._messages.moveCancelled(move.label));
      this._move = null;
    }
  }

  private _dropMove(move: IMoveState): void {
    const anchor = move.items[0];
    this._store.fDraggable?.fMoveNodes.emit(
      new FMoveNodesEvent(
        move.items.map((item) => ({ id: item.node.fId(), position: { ...item.current } })),
      ),
    );
    this._announce(
      this._messages.dropped(
        move.label,
        Math.round(anchor.current.x),
        Math.round(anchor.current.y),
      ),
    );
    this._move = null;
  }

  /**
   * `Space` works both ways: hold it and arrow — releasing drops (a quasimode, no
   * mode state to forget); or tap it — the mode stays armed until the next tap, which
   * users who cannot chord keys (single hand, sticky keys, switch access) rely on.
   */
  private _onKeyUp(event: KeyboardEvent): void {
    const move = this._move;
    if (!move || !this._matchesKey(event, this._config.keys.grab)) {
      return;
    }
    move.spaceHeld = false;
    if (move.movedWhileHeld) {
      this._dropMove(move);
    }
  }

  // ------------------------------------------------------------------ connect mode

  private _beginConnect(event: KeyboardEvent): void {
    if (!this._store.fDraggable) {
      return;
    }
    event.preventDefault();

    // A connection has exactly one source — the gesture is only meaningful when
    // exactly one node is selected; anything else would guess the source silently.
    const selection = this._selection();
    const nodeIds = [...selection.fNodeIds, ...selection.fGroupIds];
    if (nodeIds.length !== 1 || selection.fConnectionIds.length) {
      this._announce(this._messages.connectRequiresSingleNode, 'assertive');

      return;
    }

    const node = this._store.nodes.getAll().find((x) => x.fId() === nodeIds[0]);
    if (!node) {
      return;
    }

    const source = node.connectors.find(
      (x): x is FSourceConnectorBase => this._isSourceCapable(x) && x.canBeConnected,
    );
    const center = this._nodeCenter(node);
    if (!source || !this._session.begin(source, center)) {
      this._announce(this._messages.connectUnavailable, 'assertive');

      return;
    }

    const targets = [...this._session.connectableTargets].sort((a, b) => {
      const ca = a.rect.gravityCenter;
      const cb = b.rect.gravityCenter;

      return (
        Math.hypot(ca.x - center.x, ca.y - center.y) - Math.hypot(cb.x - center.x, cb.y - center.y)
      );
    });

    if (!targets.length) {
      this._session.cancel();
      this._announce(this._messages.connectUnavailable, 'assertive');

      return;
    }

    // Default to the nearest target on ANOTHER node that is NOT already connected to
    // this source — proposing the node's own connector or a duplicate edge first is
    // never what the user meant. Both stay reachable by cycling; the preference only
    // relaxes when nothing better exists.
    const sourceId = source.fId();
    const alreadyConnected = new Set<string>();
    for (const connection of this._store.connections.getAll()) {
      if (connection.sourceId() === sourceId) {
        alreadyConnected.add(connection.targetId());
      }
      if (connection.targetId() === sourceId) {
        alreadyConnected.add(connection.sourceId());
      }
    }
    const isForeign = (x: IConnectorRectRef) => !node.isContains(x.connector.hostElement);
    const isFresh = (x: IConnectorRectRef) => !alreadyConnected.has(x.connector.fId());
    const index = [
      targets.findIndex((x) => isForeign(x) && isFresh(x)),
      targets.findIndex(isForeign),
      targets.findIndex(isFresh),
      0,
    ].find((x) => x !== -1) as number;

    this._connect = {
      source,
      sourceLabel: this._nodeLabel(node),
      targets,
      index,
    };
    this._announce(this._messages.connectStarted(this._nodeLabel(node)));
    this._applyConnectTarget(this._connect);
  }

  /** A unified `[fConnector]` in `target` mode is drop-only — it must never start a connection. */
  private _isSourceCapable(connector: unknown): connector is FSourceConnectorBase {
    if (!(connector instanceof FSourceConnectorBase)) {
      return false;
    }

    return !(connector instanceof FConnectorDirective && connector.fConnectorType() === 'target');
  }

  private _handleConnectMode(event: KeyboardEvent, connect: IConnectState): void {
    const direction = ARROW_DIRECTIONS[event.key];

    if (direction) {
      event.preventDefault();
      // Same spatial model as node navigation — an arrow proposes the nearest target
      // in that direction, and the opposite arrow returns to where you came from.
      const current = connect.targets[connect.index];
      const currentId = current.connector.fId();
      const preferredId =
        connect.lastMove &&
        connect.lastMove.toId === currentId &&
        connect.lastMove.direction === oppositeOf(direction)
          ? connect.lastMove.fromId
          : undefined;

      const next = findSpatialNeighbor(
        current.rect,
        connect.targets
          .filter((x) => x !== current)
          .map((x) => ({ id: x.connector.fId(), rect: x.rect })),
        direction,
        preferredId,
      );
      if (next) {
        connect.lastMove = { fromId: currentId, toId: next.id, direction };
        connect.index = connect.targets.findIndex((x) => x.connector.fId() === next.id);
        this._applyConnectTarget(connect);
      }

      return;
    }

    if (event.key === 'Enter') {
      event.preventDefault();
      const target = connect.targets[connect.index];
      const rect = target.connector.hostElement.getBoundingClientRect();
      this._session.complete({ x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 });
      this._announce(this._messages.connected(connect.sourceLabel, this._connectorLabel(target)));
      this._connect = null;

      return;
    }

    if (event.key === 'Escape') {
      event.preventDefault();
      this._session.cancel();
      this._announce(this._messages.connectCancelled);
      this._connect = null;
    }
  }

  private _applyConnectTarget(connect: IConnectState): void {
    const target = connect.targets[connect.index];
    this._session.update(target.rect.gravityCenter);
    this._announce(
      this._messages.connectTarget(
        this._connectorLabel(target),
        connect.index + 1,
        connect.targets.length,
      ),
    );
  }

  // ------------------------------------------------------------------ zoom

  private _zoom(action: (zoom: IZoomLike) => void): void {
    const instance = this._store.instances.get(INSTANCES.ZOOM) as unknown as
      | Partial<IZoomLike>
      | undefined;
    if (!instance?.zoomIn || !instance.zoomOut || !instance.reset || !instance.getZoomValue) {
      return;
    }
    action(instance as IZoomLike);
    this._announce(this._messages.zoom(Math.round(instance.getZoomValue() * 100)));
  }

  // ------------------------------------------------------------------ shared

  private _cancelModes(): void {
    if (this._connect) {
      this._session.cancel();
      this._connect = null;
    }
    this._move = null;
  }

  private _announce(message: string, politeness: 'polite' | 'assertive' = 'polite'): void {
    this._announcer.announce(message, politeness);
  }

  private _selection(): ICurrentSelection {
    return this._mediator.execute<ICurrentSelection>(new GetCurrentSelectionRequest());
  }

  /**
   * Arrow navigation runs over plain nodes only: a group's huge bounding rect would
   * win every edge-distance comparison and swallow the navigation (and groups are
   * frequently selection-disabled). Groups stay pointer-reachable.
   */
  private _navigableNodes(): FNodeBase[] {
    return this._store.nodes.getAll().filter((x) => !this._isGroup(x) && !x.fSelectionDisabled());
  }

  private _isGroup(node: FNodeBase): boolean {
    return node.hostElement.hasAttribute('data-f-group-id');
  }

  private _activeNode(): FNodeBase | undefined {
    return this._activeNodeId
      ? this._store.nodes.getAll().find((x) => x.fId() === this._activeNodeId)
      : undefined;
  }

  private _activeConnection(): FConnectionBase | undefined {
    return this._activeConnectionId
      ? this._store.connections.getAll().find((x) => x.fId() === this._activeConnectionId)
      : undefined;
  }

  private _nodeRect(node: FNodeBase): IRect {
    return RectExtensions.initialize(
      node._position.x,
      node._position.y,
      node.hostElement.offsetWidth,
      node.hostElement.offsetHeight,
    );
  }

  private _nodeCenter(node: FNodeBase): IPoint {
    return {
      x: node._position.x + node.hostElement.offsetWidth / 2,
      y: node._position.y + node.hostElement.offsetHeight / 2,
    };
  }

  private _connectionMidpoint(connection: FConnectionBase | undefined): IPoint | undefined {
    if (!connection) {
      return undefined;
    }
    const owners = this._connectorOwners();
    const source = owners.get(connection.sourceId());
    const target = owners.get(connection.targetId());
    if (!source || !target) {
      return undefined;
    }
    const a = this._nodeCenter(source);
    const b = this._nodeCenter(target);

    return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 };
  }

  private _connectorOwners(): Map<string, FNodeBase> {
    const result = new Map<string, FNodeBase>();
    for (const node of this._store.nodes.getAll()) {
      for (const connector of node.connectors) {
        result.set(connector.fId(), node);
      }
    }

    return result;
  }

  private _nodeLabel(node: FNodeBase): string {
    return (
      node.hostElement.getAttribute('aria-label') ||
      node.hostElement.textContent?.trim().slice(0, 60) ||
      node.fId()
    );
  }

  private _connectorLabel(target: IConnectorRectRef): string {
    const element = target.connector.hostElement as HTMLElement;
    const owner = this._store.nodes.getAll().find((x) => x.isContains(element));

    return (
      element.getAttribute('aria-label') ||
      (owner ? this._nodeLabel(owner) : target.connector.fId())
    );
  }
}

function oppositeOf(direction: FA11yDirection): FA11yDirection {
  return direction === 'up'
    ? 'down'
    : direction === 'down'
      ? 'up'
      : direction === 'left'
        ? 'right'
        : 'left';
}
