import { EFConnectionBehavior, EFConnectionConnectableSide, EFConnectionType } from '@foblex/flow';
import { IUmlConnectionViewModel } from '../i-uml-model';

export const UML_CROSS_LAYER_CONNECTIONS: IUmlConnectionViewModel[] = [
  {
    id: 'conn-checkout-order-repo',
    from: 'checkout-service',
    to: 'order-repository',
    kind: 'dependency',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.BOTTOM,
    inputSide: EFConnectionConnectableSide.TOP,
    label: 'loads/saves',
  },
  {
    id: 'conn-checkout-payment-gateway',
    from: 'checkout-service',
    to: 'payment-gateway',
    kind: 'dependency',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.BOTTOM,
    inputSide: EFConnectionConnectableSide.TOP,
    label: 'charges',
  },
  {
    id: 'conn-postgres-order-repo',
    from: 'postgres-order-repository',
    to: 'order-repository',
    kind: 'realization',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.ADAPTIVE_CURVE,
    outputSide: EFConnectionConnectableSide.TOP,
    inputSide: EFConnectionConnectableSide.BOTTOM,
    label: 'implements',
  },
  {
    id: 'conn-stripe-payment-gateway',
    from: 'stripe-payment-gateway',
    to: 'payment-gateway',
    kind: 'realization',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.ADAPTIVE_CURVE,
    outputSide: EFConnectionConnectableSide.TOP,
    inputSide: EFConnectionConnectableSide.BOTTOM,
    label: 'implements',
  },
  {
    id: 'conn-projector-queries',
    from: 'read-model-projector',
    to: 'order-queries',
    kind: 'association',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.BOTTOM,
    inputSide: EFConnectionConnectableSide.TOP,
    label: 'updates read model',
  },
];
