import { EFConnectionBehavior, EFConnectionConnectableSide, EFConnectionType } from '@foblex/flow';
import { IUmlConnectionViewModel } from '../i-uml-model';

export const UML_DOMAIN_CONNECTIONS: IUmlConnectionViewModel[] = [
  {
    id: 'conn-order-order-line',
    from: 'order',
    to: 'order-line',
    kind: 'composition',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.RIGHT,
    inputSide: EFConnectionConnectableSide.LEFT,
    label: 'contains',
    sourceMultiplicity: '1',
    targetMultiplicity: '1..*',
  },
  {
    id: 'conn-order-customer',
    from: 'order',
    to: 'customer',
    kind: 'association',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.BOTTOM,
    inputSide: EFConnectionConnectableSide.TOP,
    label: 'placed by',
    sourceMultiplicity: '*',
    targetMultiplicity: '1',
  },
  {
    id: 'conn-customer-address',
    from: 'customer',
    to: 'address',
    kind: 'aggregation',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.RIGHT,
    inputSide: EFConnectionConnectableSide.LEFT,
    label: 'uses',
    sourceMultiplicity: '1',
    targetMultiplicity: '1',
  },
  {
    id: 'conn-order-money',
    from: 'order',
    to: 'money',
    kind: 'composition',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.BOTTOM,
    inputSide: EFConnectionConnectableSide.TOP,
    label: 'total',
    sourceMultiplicity: '1',
    targetMultiplicity: '1',
  },
  {
    id: 'conn-priority-order-order',
    from: 'priority-order',
    to: 'order',
    kind: 'inheritance',
    behavior: EFConnectionBehavior.FIXED,
    type: EFConnectionType.SEGMENT,
    outputSide: EFConnectionConnectableSide.TOP,
    inputSide: EFConnectionConnectableSide.BOTTOM,
    label: 'extends',
  },
];
